version: '3.8'

services:
  # === åç«¯æœåŠ¡ ===
  match-app:
    build: .
    container_name: match-app
    ports:
      - "8080:8080"
    environment:

      - TZ=Asia/Shanghai

      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/match_db?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    volumes:
      - ./videos:/app/videos
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
    restart: always

  # === æ•°æ®åº“æœåŠ¡ ===
  db:
    image: mysql:8.0
    container_name: match-db
    environment:
      # ğŸ‘‡ğŸ‘‡ğŸ‘‡ ã€å»ºè®®è¿™é‡Œä¹ŸåŠ ä¸Šã€‘ ğŸ‘‡ğŸ‘‡ğŸ‘‡
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=match_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      timeout: 10s
      retries: 10
    restart: always